import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../public/style/clashDisplay.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link rel="icon" type="image/x-icon" href="/images/logo.png" />

				<Script src="https://www.googletagmanager.com/gtag/js?id=GTM-K7C335P" />
				<Script id="google-analytics">
					{`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
 
          gtag('config', 'GTM-K7C335P');
        `}
				</Script>
			</head>

			<body className={inter.className}>{children}</body>
		</html>
	);
}
