import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../public/style/clashDisplay.css";
import Script from "next/script";
import { Navbar } from "./ui/Navbar";
import { validateRequest } from "@/utils/lucia";
import { Footer } from "./ui/Footer";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const { user, session } = await validateRequest();

	return (
		<html lang="en">
			<head>
				<link rel="icon" type="image/x-icon" href="/images/logo.png" />

				<Script src="https://www.googletagmanager.com/gtag/js?id=GTM-K7C335P" />
				<Script id="google-analytics">
					{`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
 
          gtag('config', 'GTM-K7C335P');
        `}
				</Script>
			</head>

			<body>
				<Navbar user={user} />
				{children}
				<Toaster richColors />
				<Footer />
			</body>
		</html>
	);
}
