-- AlterTable
ALTER TABLE "Event" ALTER COLUMN "image" DROP NOT NULL,
ALTER COLUMN "details" DROP NOT NULL,
ALTER COLUMN "location" DROP NOT NULL,
ALTER COLUMN "status" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Team" ALTER COLUMN "repo" DROP NOT NULL,
ALTER COLUMN "pitchStatus" DROP NOT NULL,
ALTER COLUMN "projectStatus" DROP NOT NULL;

-- AlterTable
ALTER TABLE "TeamMember" ALTER COLUMN "role" DROP NOT NULL;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "avatar" DROP NOT NULL;
